networks:
  monitoring:
    external: true
    name: observability-stack_monitoring

services:
  plex-webhook:
    build: .
    container_name: plex-webhook
    restart: always
    ports:
      - "127.0.0.1:9800:8000"
    volumes:
      - ./data:/data
    networks:
      - monitoring
