sonar.projectKey=plex-webhook
sonar.projectName=plex-webhook
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.sources=app
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/data/**
sonar.coverage.exclusions=**/*
